### ISSUE TITLE
02_tracing.sh obtain address.json without "heap_start" and "heap_end"

### ISSUE THREAD

**Issue by Clingto** [RUB-SysSec/aurora#4]
```
I ran 02_tracing.sh and obtained address.json file. But without "heap_start" and "heap_end".  Could you give me some advice?

01_afl.sh
timeout 600 $AFL_DIR/afl-fuzz -C -d -m none -i $EVAL_DIR/POC -o $AFL_WORKDIR -- $EVAL_DIR/SRC_afl/build/bin/demo

02_tracing.sh
user@9ab1c4006dca:~/share/test/test/demo_ctf$ ./rca/02_tracing.sh 
INFO: Using files at /home/user/share/test/test/demo_ctf/inputs
INFO: Generating temporary directory at /tmp/tm/
INFO: Processing 1529 files in 2 subdirs at /home/user/share/test/test/demo_ctf/inputs
INFO: Done processing 1529 files in 30.105374813079834s (on average 0.6300667063561509s per input)
INFO: STATS: traced 1529/1529 files in 30.105374813079834s with 32 cores for /home/user/share/test/test/demo_ctf/inputs
INFO: killall demo_trace
sh: 1: killall: not found
INFO: Moving files from /tmp/tm/ to /home/user/share/test/test/demo_ctf/traces
INFO: Deleting temporary directory /tmp/tm/
INFO: Cleanup time: 0.1406869888305664s
INFO: Total execution time: 30.2633535861969s
INFO: Finished tracing run
{"stack_start": 140737488216064, "stack_end": 140737488351232}
Dumping to /home/user/share/test/test/demo_ctf/addresses.json

03_rca.sh
user@9ab1c4006dca:~/share/test/test/demo_ctf/rca$ RUST_BACKTRACE=1 ./03_rca.sh 
warning: profiles for the non root package will be ignored, specify profiles at the workspace root:
package:   /home/user/aurora/root_cause_analysis/root_cause_analysis/Cargo.toml
workspace: /home/user/aurora/root_cause_analysis/Cargo.toml
    Finished release [optimized] target(s) in 0.04s
     Running `target/release/rca --eval-dir /home/user/share/test/test/demo_ctf --trace-dir /home/user/share/test/test/demo_ctf --monitor --rank-predicates`
analyzing traces
reading crashes
reading non-crashes
146 crashes and 1383 non-crashes
thread 'main' panicked at 'Could not deserialize file /home/user/share/test/test/demo_ctf/addresses.json: Error("missing field `heap_start`", line: 1, column: 62)', trace_analysis/src/trace_analyzer.rs:39:40
stack backtrace:
   0: rust_begin_unwind
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/std/src/panicking.rs:515:5
   1: core::panicking::panic_fmt
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/panicking.rs:92:14
   2: core::result::unwrap_failed
             at /rustc/657bc01888e6297257655585f9c475a0801db6d2/library/core/src/result.rs:1355:5
   3: trace_analysis::trace_analyzer::MemoryAddresses::read_from_file
   4: trace_analysis::trace_analyzer::TraceAnalyzer::new
   5: root_cause_analysis::traces::analyze_traces
   6: rca::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by Clingto** [comment]
I found traces don't have  heap_address like:
```
user@9ab1c4006dca:~/share/test/test/demo_ctf/rca$ vi tmp.txt 
Pin: pin-3.15-98253-b56e429b1
Copyright 2002-2019 Intel Corporation.
 [*] Pintool: /home/user/evaluation/pin-3.15-98253-gb56e429b1-gcc-linux/source/tools/AuroraTracer/obj-intel64/aurora_tracer.so
 [*] Target:  /home/user/evaluation/pin-3.15-98253-gb56e429b1-gcc-linux/intel64/bin/pinbin
 [+] Called parse_image on /home/user/share/test/test/demo_ctf/demo_trace
 [*] Image base: 0x0000555555554000
 [*] Load offset: 0x0000555555554000
 [*] Image entry address: 0x0000555555555140
 [*] First instruction address: 0x0000aaaaaaaa9140
 [+] Called parse_image on /lib64/ld-linux-x86-64.so.2
 [+] Called parse_image on [vdso]
 [+] Called parse_image on /lib/x86_64-linux-gnu/libc.so.6
 [*] Last instruction: 0x0000555555557804
 [+] Called jsonify
 [*] Stack: 0x7ffffffde000 - 0x7ffffffff000
 [=] Completed trace.
```
when print the address_dict in $AURORA_DIR/tracing/scripts/tracing.py
```
{'Stack': {'start': '0x7ffffffde000', 'end': '0x7ffffffff000'}}'Stack': {'start': '0x7ffffffde000', 'end': '0x7ffffffff000'}}
{'Heap': {'start': '0x55555555d000', 'end': '0x55555557e000'}, 'Stack': {'start': '0x7ffffffde000', 'end': '0x7ffffffff000'}}
{'Stack': {'start': '0x7ffffffde000', 'end': '0x7ffffffff000'}}
{'Heap': {'start': '0x55555555d000', 'end': '0x55555557e000'}, 'Stack': {'start': '0x7ffffffde000', 'end': '0x7ffffffff000'}}
{'Heap': {'start': '0x55555555d000', 'end': '0x55555557e000'}, 'Stack': {'start': '0x7ffffffde000', 'end': '0x7ffffffff000'}}
{'Heap': {'start': '0x55555555d000', 'end': '0x55555557e000'}, 'Stack': {'start': '0x7ffffffde000', 'end': '0x7ffffffff000'}}
```

**Comment by mu00d8** [comment]
This may happen when during tracing no heap is detected (consequently, no heap start and end addresses are logged). As Aurora uses these information only to filter out some noise, there is no reason for this to cause a panic.

You can try the `develop` branch, commit e0c9199cea2992f863b8527d2b343464d5267293 should fix this problem. Unfortunately, I have no working setup available right now to test the fix. Can you check whether this fixes the problem and report back to us? Thanks!

**Comment by Clingto** [comment]
Sorry about the little late.
the issue seems still exists in develop branch, commit e0c9199.

**Comment by mu00d8** [comment]
I cannot reproduce the problem locally; When using the develop branch, everything works as expected. Could you please double-check if you are on the develop branch and re-build Aurora with `cargo clean && cargo build --release`?

**Comment by mu00d8** [comment]
I assume the problem is fixed and will close this issue. If the problem still occurs, feel free to reopen it.
